### ISSUE TITLE
Screen at 150% has fields cut off

### ISSUE THREAD

**Issue by Gadgetgeek2000** [ninthwalker/saverr#10]
Not sure if you can address this. I have a 4K monitor at 150%. Screen fields are cut off. Thanks!
<img width="535" alt="screen" src="https://user-images.githubusercontent.com/5576809/79396092-02c76080-7f30-11ea-9cff-9dbef4344a6b.png">

**Comment by andytt11** [comment]
I increased the size of the program wrapper in the text file. The layout looks better but the progress bar / time remaining is still cut off.

**Comment by Gadgetgeek2000** [comment]
I'm using on my 4K screen at 150% zoom. Everything is still cut off.

**Comment by ninthwalker** [comment]
Closing this. Some other people have made better apps now than this one.
Using the basic windows forms i did here does not allow for much customizaion.
See this guys new app here. Haven't tried it, but looks good:
[PlexRipper](https://github.com/PlexRipper/PlexRipper)
