### ISSUE TITLE
Incorrect ERROR message

### ISSUE THREAD

**Issue by kfoxton** [ninthwalker/saverr#11]
When there is not enough space available in the save destination, and you attempt to download content, the error message is Connection Timed Out, instead of something like insufficient space available.

**Comment by ninthwalker** [comment]
Thanks for the report, i'll look into changing that

**Comment by ninthwalker** [comment]
Closing.
The error messages displayed in the GUI are short.cut off on purpose as the error could be too long.
You can enable debugging in the settings which will output a full error log to a file in the same directory as the app.
That will then show 'access denied' or 'there is not enough space on the disk' type of messages. Thanks!
