### ISSUE TITLE
Download titles from a list on a batch

### ISSUE THREAD

**Issue by amaurynieto** [ninthwalker/saverr#13]
So, I've been using this with great success. I was wondering it should be possible to list out the entire contents of the remote server and decide which I'd like to download from a list (as opposed to one by one) and leave it during the night to download.

My use case is we visit a cabin in the woods so I need to sync things on a NAS and during the weekends the children, the family and I get to watch things without the 1mbit/s satellite internet getting in the way of our enjoyment.

More a feature than an issue.

**Comment by ninthwalker** [comment]
That is kind of beyond the scope of the app i wrote.
As you saw in the other issue here, someone showed the code to export the d/l url's. But that comes from searching, So you would still have to search for your movies or tv shows, collect all those urls into a text file, then use a different downloader to grab them all overnight or something. Good luck!
