### ISSUE TITLE
Not showing all shared servers

### ISSUE THREAD

**Issue by N3orun** [ninthwalker/saverr#16]
Hi, for me It only shows one local and one of the 2 shared servers that I have in my shared list.

**Comment by derisor** [comment]
Same.  Not seeing any servers that were added recently even after refreshing token.

**Comment by ninthwalker** [comment]
Closing.
Others have made some better apps than what I did here.
Could try using one of theirs. I have not used this one, but it looks good:
[PlexRipper](https://github.com/PlexRipper/PlexRipper)
