### ISSUE TITLE
Quality of download

### ISSUE THREAD

**Issue by p0onage** [ninthwalker/saverr#17]
Hi, first time I've used this project and when playing the downloads video every 30 seconds the film goes all blocky and pixilated for around 15 seconds. The quality of the video file doesn't have these issues when watching from the plex server.

Has anyone else experienced this and how to I overcome this issue?

**Comment by ninthwalker** [comment]
Sorry for never replying to you =(

However, there are others who have made better apps than this one now. I have not tried it, but you could check out this one here that looks good: [PlexRipper](https://github.com/PlexRipper/PlexRipper)
