### ISSUE TITLE
Saverr closing immediately 

### ISSUE THREAD

**Issue by andytt11** [ninthwalker/saverr#18]
Computer crashed while downloading. When I try and open the program from a shortcut it just closes out while briefly showing up in the taskbar. Windows 10 pro 1903. I can open it from the master folder location but not the shortcut.

**Comment by ninthwalker** [comment]
I'm super late on replying, but you could just re-install fresh.
Others have made better apps since I created this. I have not used this one, but it looks good if you want to check it out:
[PlexRipper](https://github.com/PlexRipper/PlexRipper)
