### ISSUE TITLE
Operation Timed Out Error - Numerous times

### ISSUE THREAD

**Issue by rh535** [ninthwalker/saverr#20]
I'm trying to download one of my items at a remote location, and I keep getting this error on the file. 

Error: `09/13/2020` 08:06:23: caught exception:  at . 

It happens at various stages of the download. Sometimes 30% done, sometimes 70% done. It is a larger file at around 7GB. My computer doesn't sleep. Other files have downloaded successfully. Always smaller in file size. Any idea on how to fix this?

**Comment by ninthwalker** [comment]
Super late in replying. I did add better logging to the dubug log file though.
There are also others who have made better apps than this one now. I have not tried it, but you could check out this one here that looks good: [PlexRipper](https://github.com/PlexRipper/PlexRipper)
