### ISSUE TITLE
Download button greyed out

### ISSUE THREAD

**Issue by andytt11** [ninthwalker/saverr#22]
Computer updated through the night while saverr was running. The files completed but they were stuck as .tmp files. Removed files and went to redownload and now saverr is greyed out and when I close it out it warns me that the files will be deleted even though  they are gone. After reopening I still cannot download files.
<img width="277" alt="Capture" src="https://user-images.githubusercontent.com/69354082/103727933-8d625b00-4faa-11eb-93c4-47256401f078.PNG">

**Comment by ZombieB1309** [comment]
Same happening here, there should probably be a section on "download requirements" in the case this becomes an issue.
I've tried swapping servers, download location (was using a network directory before) and re-entering my Plex info.
Edit: Also not an issue with previous commits.

**Comment by andytt11** [comment]
Have you gotten it to work?
error log is full of caught exception:  at . 
Edit: Changed the first instance of $button_download.Enabled in the Saverr.ps1 to true, opened and closed the program, then returned it to false and it allowed me to download again. It would tell me that my downloads would be canceled even though there were none.
