### ISSUE TITLE
Downloading all Seasons or all Episodes of a singular season fails

### ISSUE THREAD

**Issue by yocalebo** [ninthwalker/saverr#23]
Hello! Program works fantastic when downloading singular items. However, I'm presented with an error when trying to either do the `dlType=allSeasons` or `dlType=allEp`.

The error I'm getting is `Download Error. HTTP status 400: The server cannot process the request because the syntax is not valid.`

It seems to fail at this line:
`$allEpData[1..($allEpData.Length -1)] | Add-BitsFile $myjob`

Unfortunately, I don't know enough about powershell to really be of any more help. Thanks!

**Comment by RipBandit** [comment]
I've experienced this too. Believe it might have something to do with the file name length?

**Comment by ninthwalker** [comment]
Sorry for not replying/fixing this ever.
There are also others who have made better apps than this one now. I have not tried it, but you could check out this one here that looks good: [PlexRipper](https://github.com/PlexRipper/PlexRipper)
