### ISSUE TITLE
Support IPv6

### ISSUE THREAD

**Issue by nireins** [ninthwalker/saverr#25]
Hi,

how can i use this tool with plex server who uses ipv6?

When i change the ip adress in the serverSettings file, nothing happens or i see an error.

Greetings.

**Comment by ninthwalker** [comment]
Sorry for not replying.

However, there are others who have made better apps than this one now. Theirs might work with ipv6 only servers.
I have not tried it, but you could check out this one here that looks good: [PlexRipper](https://github.com/PlexRipper/PlexRipper)
