### ISSUE TITLE
Get Token User Error

### ISSUE THREAD

**Issue by Ademafire** [ninthwalker/saverr#26]
![image](https://user-images.githubusercontent.com/82545144/114781380-33f29080-9d3e-11eb-994d-45e3e6d5c426.png)
I have tried every solution provided.  I keep getting error for Token when using Saverr on Windows.  
![image](https://user-images.githubusercontent.com/82545144/114781520-64d2c580-9d3e-11eb-85fe-649f331c6041.png)
Yes, i am putting in correct email/username and password. :)

**Comment by ninthwalker** [comment]
Sorry for not replying/fixing this ever. If you enabled the dubug logging there may have been more info in the logfile it creates.

However, there are others who have made better apps than this one now. I have not tried it, but you could check out this one here that looks good: [PlexRipper](https://github.com/PlexRipper/PlexRipper)
