### ISSUE TITLE
change resolution 

### ISSUE THREAD

**Issue by postmanpaul** [ninthwalker/saverr#27]
Hi there! Awsome program! but where can i change the resolution of the program, do get bigger screen and see better what episodes/moives i find with it. 

Greets!

**Comment by postmanpaul** [comment]
or get the results wider, just to see better what it finds. Just anything better then size 000.1 or some :) 

greets :)

**Comment by ninthwalker** [comment]
Sorry for not replying/fixing this ever. The windows form I used is very basic for the GUI and not much room for adjusting per different resolutions.

There are also others who have made better apps than this one now. I have not tried it, but you could check out this one here that looks good: [PlexRipper](https://github.com/PlexRipper/PlexRipper)
