### ISSUE TITLE
Windows 10 Flagged as Trojan. 

### ISSUE THREAD

**Issue by n00bydev** [ninthwalker/saverr#3]
Windows 10 decided today that Saverr includes a trojan, Trojan:Win32/Masson.A!ml

I've never had this happen before, anyone else seeing this? Just a false positive maybe?

**Comment by rowdya22** [comment]
Seconded

**Comment by shackrock** [comment]
thirded

**Comment by shackrock** [comment]
Shows as https://malware.wikia.org/wiki/Tiggre!rfn for me.  No thanks, even if it's a false positive, not worth the risk.

**Comment by ninthwalker** [comment]
Sorry for the virus flag. I believe it is flagging the .exe I compiled from the powershell script or the shortcut i included for ease of use. I scanned just the powershell .ps1 script, which is really all you need and it comes back clean. 

Maybe I will remove the .exe and shortcuts, and just put in the readme how to make them if wanting.

**Comment by ninthwalker** [comment]
My compiled .exe has been removed as an option. Just the scripts available now. No more virus warnings. =)
