### ISSUE TITLE
Download button always greyed out

### ISSUE THREAD

**Issue by Darren-Hill** [ninthwalker/saverr#30]
Not sure what's happened as this always used to work, but on both movies and TV shows I can select the server, and point it at media on them, but the download button is always greyed out. This is both for my own local servers and also for remote servers that are shared with me.

If I go to them via the normal Plex web app etc I can download stuff that way via sync, but Saverr is no longer allowing me to grab anything from them? I've tried reinstalling saverr and also resetting everything (server, user credentials, token etc) and that hasn't helped.

Can anyone give me suggestions on what else I can try to get this working again as I miss how useful it is!

Also just looked in the log, and it's full of the less than useful:

`09/04/2021 09:44:33: caught exception:  at .  `

**Comment by Guegs** [comment]
I have to assume that this issue has to do with Plex retiring the old 'SYNC' feature in favour of the new 'DOWNLOADS' (which I find do not work that great). I'm going to take a poke around the source tonight but I'm not hopeful. :'(

I'm getting the same error:

`11/12/2021 17:12:38: caught exception:  at . `

**Comment by Darren-Hill** [comment]
Thanks for the attempt :)

It could be that, although it goes back to before that was announced I think, but you may well be right.

Fingers crossed anyway, as using the current sync method to download stuff is awkward and clunky - not tried the new feature but your comments above don't inspire confidence in that either.

**Comment by Guegs** [comment]
So I managed to get it working again.

Open Saver1.ps, search for the first instance of button_download.Enabled and change the value to true.

Launch the program, close it, re-launch and it should be working again.

**Comment by Darren-Hill** [comment]
Tried it, and unfortunately made no difference. Still greyed and same error in the logs.

The change I made was in this section:

```
$button_download                 = New-Object system.Windows.Forms.Button
$button_download.Enabled         = $true
$button_download.BackColor       = "#f5a623"
$button_download.text            = "Download"
$button_download.width           = 80
$button_download.height          = 25
$button_download.location        = New-Object System.Drawing.Point(345,174)
$button_download.Font            = 'Microsoft Sans Serif,9,style=Bold'
$button_download.FlatStyle       = "Flat"
```

Is that the right place, and the only change?

**Comment by Guegs** [comment]
Yup, that's the right section. Try deleting your saverrsettings.xml as well and the re-logging in from the settings. You can also try putting the button_download.Enabled back to false.

I have family members downloading with this method that I just got working again today, so the app definitely still works.

**Comment by Darren-Hill** [comment]
I've enabled $true in all examples of the download button entry where it was set to $false, and now it's working.

Will have a play with it and find out which one is the exact one I need to tweak to really get it working, but I can take it from here.

Many thanks for the help and guidance, very glad to have this nice tool back up and running :)

**Comment by ninthwalker** [comment]
Hi guys, haven't been as active around here recently.
I have also kind of stopped updating/supporting this app.

I haven't tried it, but someone else made a better working/looking app that does this stuff now.
You can check it out here: [PlexRipper](https://github.com/PlexRipper/PlexRipper)

**Comment by ninthwalker** [comment]
I did however fix some logging in the latest version.
Not sure why the download button is not becoming clickable, i wasn't able to reproduce it.
But if you do still use this, could try the latest version and check the debug logfile. Should show more than a  period for that now.

**Comment by Darren-Hill** [comment]
Thanks. Yes I do still use it, at least when the download button is/was working.

The current fix has got it up and running again, but nice to know there are other options out there if things do stop and you are giving up on this one.

In any case, just wanted to say thanks for it. A most useful little app :)

**Comment by ninthwalker** [comment]
Glad you got some use out of it. =)
