### ISSUE TITLE
Movies with ":" in the title fail due to invalid characters

### ISSUE THREAD

**Issue by gettingerr** [ninthwalker/saverr#32]
If attempting to download a movie with a ":" in the title, it will fail. Error log is 

04/12/2022 20:20:00: caught exception: System.ArgumentException: Illegal characters in path.
   at Microsoft.BackgroundIntelligentTransfer.Management.NewBitsTransferCommand.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord() at 1649. Illegal characters in path.

It appears that movies are not checked for illegal characters like TV shows and Music are. I cannot figure out the solution due to my limited experience with powershell code. Hopefully someone else can work this out.

**Comment by ninthwalker** [comment]
Thanks for letting me know. Yea, the function to strip invalid filepath characters (like :) was missing from a couple places.
I don't really maintain this script any more, but this fix took me 2 minutes so I fixed it in the latest master branch. (v 1.1.2)

I do point people to this guys repo now though if you are looking for a better implementation than my simple script. He has made a really nice GUI and feature set for doing what my simple script did. can find his here:
https://github.com/PlexRipper/PlexRipper
