### ISSUE TITLE
Cant download all season at once, timeout

### ISSUE THREAD

**Issue by Hemps38** [ninthwalker/saverr#34]
I get a timeout trying to download ALL seasons.
Single Season download works.

Any ideas, I tried increasing Timeout in saverr.ps1

**Comment by ninthwalker** [comment]
sorry, this project isn't actively developed on any longer. Each server can be a bit different, so its possible it is not something you can fix on your end but is a timeout on the configuration or proxy it's passing through on the servers end.

Can always just download 1 season at a time if grabbing ALL is not working.
