### ISSUE TITLE
Feature Request -- Scheduled Download

### ISSUE THREAD

**Issue by papafreebird** [ninthwalker/saverr#36]
I have a feature request.  Can a download scheduler be included?  My internet service has a soft cap during daytime hours.  i have unlimited download capabilities from 11pm to 7am.  It would be very helpful to be able to schedule downloads to start during that time.

**Comment by papafreebird** [comment]
I've solved the problem myself.  I added my code below for anyone who is wanting the same feature.  You can edit it to your needs.  Just change the time as needed.  It's in military time.  Changes start at line 1442.  Basically added and if else statement.

The important part that allows it to delay downloads until a specific time is this.  After making this change I can now set up a download before going to bed and it will start at 11pm and run until completed.

```
	         # this delays downloads until after 11pm
             $time = Get-Date '23:00'
             $now = Get-Date
			 
			 
		if ($now -le $time)
        {
			$label_DLTitle.Text = "Waiting until 11pm . . ."
			(New-TimeSpan -End $time).TotalSeconds | Sleep;
....existing download code goes here
       }
else {exiting download code}
```

[Saverr-dl-later2.txt](https://github.com/ninthwalker/saverr/files/10471208/Saverr-dl-later2.txt)

**Comment by ninthwalker** [comment]
Thanks for leaving the code for anyone else who wanted something like this. Glad you figured out how to do it.
