### ISSUE TITLE
Errors cut off in the window, no wrap text

### ISSUE THREAD

**Issue by shackrock** [ninthwalker/saverr#4]
Can't see the error messages because they are cut off in the window and not "word wrapped" - see screenshot below.

![image](https://user-images.githubusercontent.com/559901/74110357-ca835a80-4b59-11ea-81b0-fe2e03048ce5.png)

**Comment by ninthwalker** [comment]
If I don't get around to fixing/changing that behavior, there is always the debug option in settings. That will output full info and errors to a log file in the same directory as the script.

**Comment by ninthwalker** [comment]
Closing this. looked into expanding the output of that field, but i added on the ellipse (...) on purpose i realized so it doesn't cut off other fields if they are showing at the same time.
Tried to keep the app window relatively small. As mentioned before, just enable debugging and check the log file for the full output. Thanks!
