### ISSUE TITLE
Check for existing files?

### ISSUE THREAD

**Issue by natelabo** [ninthwalker/saverr#7]
Hello... Thanks for the great little app! Wondering if it would be possible to do a check to see if a file exists before grabbing?

I found that I will typically try to download whole seasons. Sometimes these will fail 1/2 way through. From there I have to select each episode individually or try and grab the whole season all over again.

I looked for a way to add the logic. But unfortunately I'm not the greatest at programming. Let me know if this would be an option.

I can continue to work on it if you don't have the time. Thanks!

**Comment by ninthwalker** [comment]
This has been implemented in the latest version (1.1.0)
It will first check for existing files, and then skip them when adding the downloads to the job.
Should make resuming large downloads faster now. Thanks for the input.
